# nginx/nginx.conf

# Definimos que nuestro contenedor 'web' (Python) servirá la data
upstream flask_app {
    server web:5000;
}

server {
    # Nginx escucha peticiones en el puerto 80 estándar
    listen 80;

    # Bloque para peticiones normales HTTP de la página web
    location / {
        proxy_pass http://flask_app;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Bloque ESPECIAL para soportar SocketIO (el chat y el proxy en vivo)
    location /socket.io {
        # proxy_pass a http://flask_app sin uri final para que Nginx mantenga el string de querystring intacto
        proxy_pass http://flask_app;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
